#
# version.cmake : version du projet
#

set (PREFERENCES_MAJOR_VERSION "6")
set (PREFERENCES_MINOR_VERSION "3")
set (PREFERENCES_RELEASE_VERSION "0")
set (PREFERENCES_VERSION ${PREFERENCES_MAJOR_VERSION}.${PREFERENCES_MINOR_VERSION}.${PREFERENCES_RELEASE_VERSION})


